[package]
name = "lw06_uniforms_3d_camera"
version = "0.1.0"
authors = ["CatCode79 https://github.com/CatCode79"]
edition = "2021"
description = "based on https://sotrh.github.io/learn-wgpu/beginner/tutorial6-uniforms/"
publish = false

[dependencies]
env_logger = "0.9"
irid = { git = "https://github.com/CatCode79/irid-framework" }
irid-assets = { git = "https://github.com/CatCode79/irid-framework" }
log = "0.4"
wgpu = "0.11"
winit = "0.25"
